CREATE DATABASE IF NOT EXISTS atd_bingo_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE atd_bingo_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NULL,
    name VARCHAR(150) NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    mac_address VARCHAR(50) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS generated_licenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    alias_name VARCHAR(100) NULL,
    mode VARCHAR(50) NOT NULL,
    action_details TEXT NOT NULL,
    mac_address VARCHAR(50) NULL,
    topup_amount DECIMAL(15, 2) NULL DEFAULT 0.00,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
